sonar.projectKey=spaul-12_7.3HD
sonar.organization=spaul-12
sonar.host.url=https://sonarcloud.io
sonar.token=${SONAR_TOKEN}

sonar.sources=.
sonar.exclusions=env/**,test_app.py
sonar.python.coverage.reportPaths=coverage.xml

sonar.projectName=Flask CRUD API
sonar.sourceEncoding=UTF-8